import { CARDS_CODES } from "../../constants";
import { GameState, Room } from "../../types";

export const INITIAL_ROOM_STUB: Room = {
  id: "abc123",
  table: [],
  creationDate: new Date("01-01-2024"),
  gameState: GameState.WaitingForPlayers,
  players: [
    {
      id: "p1",
      nickname: "Player 1",
      cards: [],
      collectedCards: [],
      currentBrushCount: 0,
      isOwner: true,
      previousPoints: 0,
    },
  ],
  cards: [...CARDS_CODES],
};

export const IN_GAME_ROOM_STUB: Room = {
  id: "abc123",
  creationDate: new Date("01-01-2024"),
  gameState: GameState.Playing,
  players: [
    {
      id: "p1",
      nickname: "Player 1",
      cards: ["QD", "5S", "6S"],
      collectedCards: [],
      currentBrushCount: 0,
      isOwner: true,
      previousPoints: 0,
    },
    {
      id: "p2",
      nickname: "Player 2",
      cards: ["QS", "4S", "2D"],
      collectedCards: [],
      currentBrushCount: 0,
      isOwner: false,
      previousPoints: 0,
    },
  ],
  table: ["7S", "AD", "2C", "3C"],
  cards: [
    "AS",
    "2S",
    "3S",
    "JS",
    "KS",
    "3D",
    "4D",
    "5D",
    "6D",
    "7D",
    "JD",
    "KD",
    "AC",
    "4C",
    "5C",
    "6C",
    "7C",
    "JC",
    "QC",
    "KC",
    "AH",
    "2H",
    "3H",
    "4H",
    "5H",
    "6H",
    "7H",
    "JH",
    "QH",
    "KH",
  ],
  currentTurn: "Player 1",
  firstPlayerNick: "Player 1",
};

export const ROUND_OVER_ROOM_STUB: Room = {
  id: "abc123",
  creationDate: new Date("01-01-2024"),
  gameState: GameState.RoundOver,
  players: [
    {
      id: "p1",
      nickname: "Player 1",
      cards: [],
      collectedCards: [
        "5C",
        "4D",
        "AS",
        "5H",
        "2S",
        "3S",
        "KS",
        "3D",
        "5D",
        "7D",
        "KD",
        "AC",
        "4C",
        "JD",
        "6C",
        "KH",
        "5S",
      ], //17
      currentBrushCount: 1,
      isOwner: true,
      previousPoints: 5,
    },
    {
      id: "p2",
      nickname: "Player 2",
      cards: [],
      collectedCards: [
        "2D",
        "7S",
        "AD",
        "2C",
        "3C",
        "JS",
        "6D",
        "7C",
        "QC",
        "2H",
        "6H",
        "7H",
        "KC",
        "AH",
        "4H",
        "QS",
        "4S",
        "3H",
        "JC",
        "6S",
      ], //20
      currentBrushCount: 1,
      isOwner: false,
      previousPoints: 4,
    },
  ],
  table: ["JH", "QH", "QD"],
  cards: [],
};
