import { Card } from "shared-types";

export const CARDS: Card[] = [
  {
    code: "AS",
    image: "/resources/cards/default_webp/AS.webp",
    value: "ACE",
    suit: "SPADES",
  },
  {
    code: "2S",
    image: "/resources/cards/default_webp/2S.webp",
    value: "2",
    suit: "SPADES",
  },
  {
    code: "3S",
    image: "/resources/cards/default_webp/3S.webp",
    value: "3",
    suit: "SPADES",
  },
  {
    code: "4S",
    image: "/resources/cards/default_webp/4S.webp",
    value: "4",
    suit: "SPADES",
  },
  {
    code: "5S",
    image: "/resources/cards/default_webp/5S.webp",
    value: "5",
    suit: "SPADES",
  },
  {
    code: "6S",
    image: "/resources/cards/default_webp/6S.webp",
    value: "6",
    suit: "SPADES",
  },
  {
    code: "7S",
    image: "/resources/cards/default_webp/7S.webp",
    value: "7",
    suit: "SPADES",
  },
  {
    code: "JS",
    image: "/resources/cards/default_webp/JS.webp",
    value: "JACK",
    suit: "SPADES",
  },
  {
    code: "QS",
    image: "/resources/cards/default_webp/QS.webp",
    value: "QUEEN",
    suit: "SPADES",
  },
  {
    code: "KS",
    image: "/resources/cards/default_webp/KS.webp",
    value: "KING",
    suit: "SPADES",
  },
  {
    code: "AD",
    image: "/resources/cards/default_webp/AD.webp",
    value: "ACE",
    suit: "DIAMONDS",
  },
  {
    code: "2D",
    image: "/resources/cards/default_webp/2D.webp",
    value: "2",
    suit: "DIAMONDS",
  },
  {
    code: "3D",
    image: "/resources/cards/default_webp/3D.webp",
    value: "3",
    suit: "DIAMONDS",
  },
  {
    code: "4D",
    image: "/resources/cards/default_webp/4D.webp",
    value: "4",
    suit: "DIAMONDS",
  },
  {
    code: "5D",
    image: "/resources/cards/default_webp/5D.webp",
    value: "5",
    suit: "DIAMONDS",
  },
  {
    code: "6D",
    image: "/resources/cards/default_webp/6D.webp",
    value: "6",
    suit: "DIAMONDS",
  },
  {
    code: "7D",
    image: "/resources/cards/default_webp/7D.webp",
    value: "7",
    suit: "DIAMONDS",
  },
  {
    code: "JD",
    image: "/resources/cards/default_webp/JD.webp",
    value: "JACK",
    suit: "DIAMONDS",
  },
  {
    code: "QD",
    image: "/resources/cards/default_webp/QD.webp",
    value: "QUEEN",
    suit: "DIAMONDS",
  },
  {
    code: "KD",
    image: "/resources/cards/default_webp/KD.webp",
    value: "KING",
    suit: "DIAMONDS",
  },
  {
    code: "AC",
    image: "/resources/cards/default_webp/AC.webp",
    value: "ACE",
    suit: "CLUBS",
  },
  {
    code: "2C",
    image: "/resources/cards/default_webp/2C.webp",
    value: "2",
    suit: "CLUBS",
  },
  {
    code: "3C",
    image: "/resources/cards/default_webp/3C.webp",
    value: "3",
    suit: "CLUBS",
  },
  {
    code: "4C",
    image: "/resources/cards/default_webp/4C.webp",
    value: "4",
    suit: "CLUBS",
  },
  {
    code: "5C",
    image: "/resources/cards/default_webp/5C.webp",
    value: "5",
    suit: "CLUBS",
  },
  {
    code: "6C",
    image: "/resources/cards/default_webp/6C.webp",
    value: "6",
    suit: "CLUBS",
  },
  {
    code: "7C",
    image: "/resources/cards/default_webp/7C.webp",
    value: "7",
    suit: "CLUBS",
  },
  {
    code: "JC",
    image: "/resources/cards/default_webp/JC.webp",
    value: "JACK",
    suit: "CLUBS",
  },
  {
    code: "QC",
    image: "/resources/cards/default_webp/QC.webp",
    value: "QUEEN",
    suit: "CLUBS",
  },
  {
    code: "KC",
    image: "/resources/cards/default_webp/KC.webp",
    value: "KING",
    suit: "CLUBS",
  },
  {
    code: "AH",
    image: "/resources/cards/default_webp/AH.webp",
    value: "ACE",
    suit: "HEARTS",
  },
  {
    code: "2H",
    image: "/resources/cards/default_webp/2H.webp",
    value: "2",
    suit: "HEARTS",
  },
  {
    code: "3H",
    image: "/resources/cards/default_webp/3H.webp",
    value: "3",
    suit: "HEARTS",
  },
  {
    code: "4H",
    image: "/resources/cards/default_webp/4H.webp",
    value: "4",
    suit: "HEARTS",
  },
  {
    code: "5H",
    image: "/resources/cards/default_webp/5H.webp",
    value: "5",
    suit: "HEARTS",
  },
  {
    code: "6H",
    image: "/resources/cards/default_webp/6H.webp",
    value: "6",
    suit: "HEARTS",
  },
  {
    code: "7H",
    image: "/resources/cards/default_webp/7H.webp",
    value: "7",
    suit: "HEARTS",
  },
  {
    code: "JH",
    image: "/resources/cards/default_webp/JH.webp",
    value: "JACK",
    suit: "HEARTS",
  },
  {
    code: "QH",
    image: "/resources/cards/default_webp/QH.webp",
    value: "QUEEN",
    suit: "HEARTS",
  },
  {
    code: "KH",
    image: "/resources/cards/default_webp/KH.webp",
    value: "KING",
    suit: "HEARTS",
  },
];

export const CARDS_CODES = CARDS.map((card) => card.code);
